### ISSUE TITLE
getIPBans doesn't return the date a ban was issued

### ISSUE THREAD

**Issue by Lavode** [pdaian/MCBouncer#12]
Right now the response you get from the API looks something like this:

```
{'totalcount': 1, 'data': [{'ip': '8.8.8.8', 'reason': 'Go away, Google', 'server': 'minecraft.lethal-zone.eu', 'issuer': 'morrolan'}], 'page': 0, 'success': True, 'error': ''}
```

As can be seen, the response does not contain the date a specific IP ban was issued.
Since the date a player ban was issued does get shown, I suppose that's not intended behaviour. :)

**Comment by Deaygo** [comment]
This is now fixed :)
